name: Auto-diff PDF files

# only trigger on opened/reopened PRs that change the schematic
on:
  pull_request:
    types:
      - opened
      - reopened
    paths:
      - '**.kicad_sch'

jobs:
  diff_pdfs:
    runs-on: ubuntu-latest
    name: Render diffs of schematics
    steps:
    - name: Checkout
      uses: actions/checkout@v2
