name: Render .drawio files
# slightly modified from the example in https://github.com/marketplace/actions/drawio-rendering-action

on: [push]

jobs:
  render_drawio:
    runs-on: ubuntu-latest
    name: Render .drawio files
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Render .drawio files
      uses: docker://ghcr.io/racklet/render-drawio-action:v1
      with:
        formats: 'png'
      id: render
    - name: List the rendered files
      run: 'ls -l ${{ steps.render.outputs.rendered-files }}'
    - name: Commit the rendered files
      uses: EndBug/add-and-commit@v7
      with:
        # This makes the GH Actions user/bot the author of the commit
        default_author: github_actor
        message: 'Automatically render .drawio files'
        add: "${{ steps.render.outputs.rendered-files }}"
      if: "${{ steps.render.outputs.rendered-files != ''}}"
